### ISSUE TITLE
labcompass got stuck in corner

### ISSUE THREAD

**Issue by vjru5zl0v3** [yznpku/LabCompass#1]
as title, labcompass got stuck in my corner, i try everthing but no chance to move it anywhere because it dont have window tile bar or even icon so i can right click to choose "move" option

**Comment by zocke1r** [comment]
you can move it by holding the name plate

**Comment by vjru5zl0v3** [comment]
The problem here is name plate, as said "window tittle bar" and it stuck at corner. I cant click it anymore so i cant move labcompass. It outside of my screen...

**Comment by zocke1r** [comment]
ah okay, in that case changing the main window position might help, this is done by opening the options.json, and changing the values of "mainWindowPosition" to something on your screen, 0,0 is top left corner

**Comment by vjru5zl0v3** [comment]
Okay, it work now, sorry for my bad english, sometime it hard for me to explain what i want to say. Where i can give some suggestion to labcompass? Not using github much and this is first time i comment there.
