### ISSUE TITLE
Does not start tracking [golden doors]

### ISSUE THREAD

**Issue by Camelket** [yznpku/LabCompass#11]
Did not start tracking for me on the 15.01.18 during the merciless lab that had golden doors in it. Restarting and redownloading the files did not change a thing. Worked on another difficulty lab (without golden doors) without problems.

**Comment by yznpku** [comment]
Can you upload the (json) file you were using? Thank you.

**Comment by Camelket** [comment]
[merciless 15.01.18.zip](https://github.com/yznpku/LabCompass/files/1655514/merciless.15.01.18.zip)

**Comment by yznpku** [comment]
Seem to have been fixed in 1.1.0 release.
