### ISSUE TITLE
"Game Client File" is impossible to configure for Steam

### ISSUE THREAD

**Issue by hoha** [yznpku/LabCompass#15]
Version 1.1.0

Client file name is hardcoded as Client.exe in the configuration dialog but it can also be PathOfExileSteam.exe or PathOfExile_x64Steam.exe for Steam distributions. Also the path field is not editable so it is not possible to paste the path directly

**Comment by ccomly** [comment]
v 1.1.1 cant select the 64bit steam executable 

PathOfExile_x64Steam.exe

**Comment by IntoEnto** [comment]
likewise, also point out there is also a 64x client too.
