### ISSUE TITLE
Path selecting is broken?

### ISSUE THREAD

**Issue by madkumamon** [yznpku/LabCompass#17]
![image](https://user-images.githubusercontent.com/13980081/35339592-a4c49fc4-0129-11e8-89cf-2c783d9fd734.png)

Can't select path from step 1 to end if I want to select path by myself I need to go with stars from end to start. Its feature or bug ? Also Argus not displayed in sidebar when selected.

P.S. But we anyway love you @yznpku !!! <3 Thas awesome plugin!

**Comment by yznpku** [comment]
With 1.1.0 release manual path selecting is no longer a thing. You have to "star" rooms and the path will be calculated for you.

In your screenshot you are on location overriding mode (the red marker). That mode is used to tell the program your current location. You won't need it in most cases.

Plan summary is only calculated when you are actually planning things before you enter the labyrinth. Once you enter, these number won't change anymore.

**Comment by madkumamon** [comment]
@yznpku, awesome, thank you!
