### ISSUE TITLE
add parsing of xml files (someone uploaded xml on poelab.com)

### ISSUE THREAD

**Issue by sudosWoW** [yznpku/LabCompass#2]
Today it shows only a black screen and does not load the layout. 
This is because someone uploaded an xml file instead of json (but named it .json) to poelab.com

maybe you can check for the file content/type and also parse a xml file ? 

[uber (3).zip](https://github.com/yznpku/LabCompass/files/1563374/uber.3.zip)

**Comment by yznpku** [comment]
It seems to be a mistake on the website. LabCompass never meant to take formats other than JSON.
