### ISSUE TITLE
Compass overlay not opening when switching from connected external screen to laptop only

### ISSUE THREAD

**Issue by Khezztwo** [yznpku/LabCompass#24]
Title says it already. I am running two setups in different locations. One is my laptop only with 1366X768, the other one is on a docking station with external screens where it is scaled up to 1920X1080. 

On the external screen lapcompass runs without any problem, but once I disconnect the external and "scale" back to the normal laptop screen resolution, the overlay doesn't open anymore (but the process is running fine). Since the scaling moves my icons around, too, I thought moving the overlay box into a different corner which seems not to get changed helps but it won't. Does anybody have an idea how to work around it? Deleting the file and re-extracting it etc didn't help so far.

I appreciate any suggestions, but will try again to simply move it around to different corners of my screen when switching between external <> laptop.

**Comment by yznpku** [comment]
For now try reset the settings by deleting the registry entries.

1. Open registry editor (win+R, type "regedit" in it)

1. Go to HKEY_CURRENT_USER\Software\FutureCode\LabCompass

1. Delete everything in it

**Comment by Khezztwo** [comment]
Thank you. I figured out it is all about the positioning of the overlay when you close it on the extended screen - just needs to be closed in an area covered by the smaller resolution when on laptop only... :)
