### ISSUE TITLE
Path is broken when taking the new darkshrine portals to Izaro

### ISSUE THREAD

**Issue by miaXcova** [yznpku/LabCompass#5]
The program does not seem to recover, and likely this would be difficult to track.  I suggest allowing the user to manually reset their current position while inside the labs and reinitialize the plan from the new location.

**Comment by miaXcova** [comment]
I think the path also breaks when using shortcuts.  Furthermore, if the shortcut info is not in the json file, I cannot imagine this being easy to track.

Either way, a manual reset of current position should cover both these scenarios.

**Comment by FiftyCaliber** [comment]
This could be fixed using the same method used for detecting the area your in. By having the app detect "A portal to Izaro appears." in Client.txt you can have it understand the location change if the player decides to enter the portal.

I'm sure you already know this but figured I would mention it anyway just in case the idea skipped your mind.

**Comment by miaXcova** [comment]
Thanks for the auto check and manual reset of map position.  That is a nice compromise.  I trigger it a lot when backtracking or on layouts with two gold door rooms with something interesting in both.

**Comment by yznpku** [comment]
Fixed in 1.2.0.
