### ISSUE TITLE
[Suggestion] Auto Update Lab Notes

### ISSUE THREAD

**Issue by miaXcova** [yznpku/LabCompass#6]
Since the link never seems to change from 
`http://www.poelab.com/wp-content/labfiles/normal.json` for Normal
`http://www.poelab.com/wp-content/labfiles/cruel.json` for Cruel
`http://www.poelab.com/wp-content/labfiles/merciless.json` for Merciless
`http://www.poelab.com/wp-content/labfiles/uber.json` for Uber/Eternal
I'd like to suggest adding **N C M U** buttons that would connect to these links directly and automatically update based on the `"date": "2018-01-03"` field inside the json file after comparing the date with what is currently loaded.  

You could also automatically perform this update on startup of the program based on the difficulty level that was previously selected.  This could mitigate issues of people locally saving the file incorrectly as well as issues with the source file being invalid.  Since the program would scan the file on load it could throw up an error that the file is unavailable, invalid or has not been updated yet.

Naturally, the option to manually load the file should remain, just as it is now.

**Comment by Doomgull** [comment]
It would have to consider that reset happens at different times of day and different dates depending on time zone, though.

**Comment by miaXcova** [comment]
Well, the date in the json file should always be in a consistent tz, so that should be the only one that is compared with.  You are already storing the json file date so compare that with the new file.  The local time/date really doesn't matter for this purpose.

But I am not talking about an automatic pull, if that is what you were thinking.  The pull would still have to be manually triggered by the user in the form of, as I suggested, NCMU buttons or on startup using the previously loaded difficulty as the current default.

**Comment by kevindevm** [comment]
and never visit poelab.com? how do u think the pay for the host? suport poelab and visit the page whitout adblock

**Comment by yznpku** [comment]
I should mention it is poelab.com generating lab data every day and exposing them all for free that makes LabCompass possible. I don't really want to hurt their daily visits and potential ads income with some auto update feature. Sorry about that and thank you for your understanding.

**Comment by Eruyome** [comment]
@yznpku I'd like to ask you to reconsider adding a feature to update the JSON from the app, at least via button. If it's about the the missed poelab pagevisits just add a forced one, opening the site in the users default browser on button use. It simply isn't convenient to manually download the files and select them via file select dialog.

**Comment by Doomgull** [comment]
Yeah, man, those four clicks you need to make after hitting the "Get Maps" button already in the tool to download the json and load it into the compass are just super unnecessary and such an inconvenience. /s

**Comment by Eruyome** [comment]
Yes they are. I'm not saying this is something that absolutely needs to be implemented but it's not unreasonable either. Mostly because the file dialog doesn't always seem to remember the last folder used and I have to navigate to the right one again and then find the correct file. Finding that file is annoying since it lands in my download folder that often has quite some other stuff in it and it doesn't overwrite the last download but saves it with the date in the filename. Over time it accumulates a lot of these files which I have to manually manage/delete.

That's just not userfriendly comapred to saving it to memory/some windows temp folder and automatically reading and cleaning it. And there's nothing wrong with wanting a more userfriendly app, isn't it?

**Comment by Doomgull** [comment]
1.2.1 added remembering the directory newrly two weeks ago.

And my jsons don't download with the date in the name from poelab, just the xdifficulty"

**Comment by miaXcova** [comment]
In the last couple days poelab also changed up their download URL to include the date - probably to combat the many people who can't ctrl-F5 to get the new labcompass file - so this entire thread is essentially moot.  Even if it were to not affect poelab's revenue stream, I still invite to close this issue.
