### ISSUE TITLE
Lab file loads but stops working when i enter lab

### ISSUE THREAD

**Issue by AppleJuicifer** [yznpku/LabCompass#69]
So when I enter the plaza it lets me know that its loaded the lab file. It then says enter lab, but as soon as I open the lab and enter it  
there's no longer any feedback from the overlay.

Not sure what could be wrong I've only had this problem in the latest league

**Comment by redrios** [comment]
I have the same problem, tried both vulkan and directx 11 fullscreen windowed

**Comment by AppleJuicifer** [comment]
I found my problem by looking through some of the bigger problems on the PoELab discord.
I had output dialogue to chat disabled. 
After enabling it my problem was fixed
