### ISSUE TITLE
[Bug/Suggestion] Multi-client Support

### ISSUE THREAD

**Issue by FiftyCaliber** [yznpku/LabCompass#9]
If running lab while you have a second client open (or more however to my knowledge running more then 2 is against GGG's rules) LabCompass works fine unless you switch areas with the second client (like if your making a trade and you leave your hideout to go to their's).

After taking a quick look at the Client.txt I see that it logs the clients with different numbers. If you could find the time it would be awesome if you would make the compass on lab start store the client number as a variable ignoring logs from other client numbers until the lab is completed?

**Comment by miaXcova** [comment]
Good suggestion.  I had a friend of mine tell me the exact thing the other day.
